apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: blog-back
  template:
    metadata:
      labels:
        app: blog-back
    spec:
      containers:
      - name: blog-back
        image: lh0ss/blog-back:1.3
        ports:
        - name: http
          containerPort: 80  
       
