apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-front-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: blog-front
  template:
    metadata:
      labels:
        app: blog-front
    spec:
      containers:
      - name: blog-front
        image: lh0ss/blog-front:1.4 
        ports:
        - containerPort: 80

