apiVersion: v1
kind: Service
metadata:
  name: blog-front-app-service  # Replace with your desired service name
spec:
  selector:
    app: blog-front  # Matches the label of your deployment pod
  ports:
  - protocol: TCP
    port: 80  # Matches the container port of your application
    targetPort: 80  # Matches the container port of your application
  type: LoadBalancer  # Specifies the service type as LoadBalancer

